ARG APP_NAME=thanos

FROM rust AS build
RUN apt-get update \
  && apt-get install -y --no-install-recommends ca-certificates gcc libssl-dev

ARG APP_NAME
WORKDIR /${APP_NAME}

COPY leakybucket/Cargo.lock Cargo.lock
COPY leakybucket/Cargo.toml Cargo.toml
COPY leakybucket/src src

RUN cargo build --locked --release
CMD ["/leakybucket/target/release/leakybucket"]