apiVersion: skaffold/v4beta5
kind: Config
metadata:
  name: rate-limiter
build:
  artifacts:
    - image: checkout 
      ko:
        main: ./checkout/cmd/checkout
    - image: thanos
      docker:
        dockerfile: docker/Dockerfile.thanos
manifests:
  rawYaml:
    #Checkout 
    - deploy/checkout/deployment.yml
    - deploy/checkout/service.yml

    # Thanos
    - deploy/thanos/deployment.yml
    - deploy/thanos/service.yml

deploy:
  helm:
    releases:
      - name: redis
        repo: https://charts.bitnami.com/bitnami 
        remoteChart: redis
        valuesFiles:
          - deploy/redis/values.yml
