apiVersion: skaffold/v4beta5
kind: Config
metadata:
  name: rate-limiter
build:
  artifacts:
    - image: thanos
      ko:
        main: ./thanos/cmd/thanos
manifests:
  rawYaml:

    # Thanos
    - deploy/thanos/deployment.yml
    - deploy/thanos/service.yml

deploy:
  helm:
    releases:
      - name: redis
        repo: https://charts.bitnami.com/bitnami 
        remoteChart: redis
        valuesFiles:
          - deploy/redis/values.yml
