apiVersion: skaffold/v4beta5
kind: Config
metadata:
  name: rate-limiter
build:
  artifacts:
    - image: checkout 
      ko:
        main: ./checkout/cmd/checkout
    - image: thanos
      docker:
        dockerfile: docker/Dockerfile.thanos
manifests:
  rawYaml:
    # Redis
    - deploy/redis/configmap.yml
    - deploy/redis/service.yml
    - deploy/redis/statefulset.yml
    - deploy/redis/pdb.yml

    # Thanos 
    - deploy/thanos/deployment.yml
    - deploy/thanos/service.yml

    # Checkout 
    - deploy/checkout/deployment.yml
    - deploy/checkout/service.yml
