apiVersion: apps/v1
kind: Deployment
metadata:
  name: thanos 
  labels:
    app: thanos 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: thanos 
  template:
    metadata:
      labels:
        app: thanos 
    spec:
      containers:
      - name: thanos 
        image: thanos
        ports:
        - containerPort: 8080
          name: thanos 
      #   volumeMounts:
      #   - mountPath: /redis-config
      #     name: config
      # volumes:
      #   - name: redis-secrets
      #     secrets:
      #       name: tredis-secrets
