apiVersion: apps/v1
kind: Deployment
metadata:
  name: checkout
  labels:
    app: checkout
spec:
  replicas: 1
  selector:
    matchLabels:
      app: checkout
  template:
    metadata:
      labels:
        app: checkout
    spec:
      containers:
      - name: checkout
        image: checkout
        ports:
        - containerPort: 8080
          name: checkout
      initContainers:
        - name: thanos
          image: thanos
          restartPolicy: Always